Fix brew audit issue in Formula/yq@2.4.1.rb
gocardless/taps/yq@3.4.1
Error: 1 problem in 1 formula detected.
  * Formula yq@2.4.1 should also have a conflict declared with yq@3.4.1