Calling GitHub.open_api is deprecated!
Use GitHub::API.open_rest instead.

Avoid the following error.

```
Error: Calling GitHub.open_api is deprecated! Use GitHub::API.open_rest instead.
Please report this issue to the gocardless/taps tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/gocardless/homebrew-taps/lib/gc/github_private_release_download_strategy.rb:70
```