Use a more modern method to authenticate
This is causing CI to fail with these errors:

✘ Formula utopia (37.6.0)
Error: Failed to download resource "utopia (37.6.0)"
Download failed: https://***@api.github.com/repos/gocardless/utopia/releases/assets/305492902

✘ Formula anu (34.0.1)
Error: Failed to download resource "anu (34.0.1)"
Download failed: https://***@api.github.com/repos/gocardless/anu/releases/assets/315043380